# Generated by Django 2.0.2 on 2018-03-04 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='company',
            new_name='publisher',
        ),
    ]
